{{- if .Values.fileLoad.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-job.fullname" . }}-config
  labels:
    {{- include "helm-job.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
{{- end }}
