{{- if or .Values.files .Values.binaryFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-job.fullname" . }}
  labels:
    {{- include "helm-job.labels" . | nindent 4 }}
data:
{{- range .Values.files }}
{{- range $key, $value := .data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
binaryData:
{{- range .Values.binaryFiles }}
{{- range $key, $value := .data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
{{- end }}

