apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-job.fullname" . }}
  labels:
    {{- include "helm-job.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-job.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          {{- if .Values.command }}        
          command: {{ .Values.command }}
          {{- end }}
          
          {{- if .Values.args }}
          args: {{ .Values.args }}
          {{- end }}

          env:
                {{- if .Values.JAVA_OPTS }}
            - name: JAVA_OPTS
              value: {{ join " " .Values.JAVA_OPTS | quote }}
                {{- end }}
                {{- if .Values.JMX_OPTS }}
            - name: JMX_OPTS
              value: {{ join " " .Values.JMX_OPTS | quote }}
                {{- end }}
                {{- range $name, $value := .Values.env }}
                {{- if not (empty $value) }}
            - name: {{ $name }}
              value: {{ $value | quote }}
                {{- end }}
                {{- end }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- range . }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
              {{ if .subPath }}subPath: {{ .subPath }}{{ end }}
            {{- end }}
            {{- end }}

            {{- if .Values.files }}
            {{- range .Values.files }}
            - mountPath: {{ .mountPath }}
              name: files
              {{- range $name, $value := .data }}
              subPath: ..data/{{ $name }}
              {{- end }}
            {{- end }}
            {{- end }}

            {{- if .Values.binaryFiles }}
            {{- range .Values.binaryFiles }}
            - mountPath: {{ .mountPath }}
              name: files
              {{- range $name, $value := .data }}
              subPath: ..data/{{ $name }}
              {{- end }}
            {{- end }}
            {{- end }}
                  
            {{- if .Values.fileLoad.enabled }}
            - mountPath: {{ .Values.fileLoad.mountPath }}
              name: files-config
            {{- end }}

            {{- if .Values.lifecycle }}
          lifecycle:
            {{- toYaml .Values.lifecycle | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if or .Values.files .Values.binaryFiles }}
        - name: files
          configMap:
            name: {{ include "helm-job.fullname" . }}
      {{- end }}
      {{- if .Values.fileLoad.enabled }}
        - name: files-config
          configMap:
            name: {{ include "helm-job.fullname" . }}-config      
      {{- end }}
